url1: "https://www.windguru.cz/station/"
url2: "https://www.windguru.cz/int/iapi.php?q=station_data_current&id_station="
stationId: 2736
interval: 20
timesBelowLimit: 30
timesAboveLimit: 90
databaseName: "Windseeker"
userCollection: "Users"
dataCollection: "Data"

mongohost: "host.docker.internal"
mongoport: 27017

logLevel: 10