name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # or whatever version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install requests pymongo pyyaml pydantic
          pip3 install pydantic[email] dotenv
          pip3 install Flask flask_cors jsonify flasgger # for web app
          pip3 install schedule colorlog
          pip3 install flake8 bcrypt
          pip3 install -U selenium webdriver-manager
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          pip install pytest

      - name: List all installed packages
        run: pip3 list

      - name: Run tests
        run: |
          pytest tests
